shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/myshop/urls.py
from django.urls import path
from . import views

app_name = 'myshop'

urlpatterns = [
    path('', views.index, name='index'), 
    path('about/', views.about, name='about'), 
    path('product/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail,name='product_detail')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace='shop'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/myshop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True, verbose_name='Наименование')
    slug = models.CharField(max_length=150, db_index=True, unique=True, verbose_name='Ссылка')
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')
    uploaded = models.DateTimeField(auto_now=True, verbose_name='Изменения')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return  self.name


    def get_absolute_url(self):
        return reverse('myshop:product_detail', args=[self.id, self.slug])

shop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

shop/myshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products,
                      'category_slug': category_slug 
                  })


def product(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products,
                      'category_slug': category_slug 
                  })

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})



def index(request):
    return render(request, 'shop/product/index.html')

def about(request):
    return render(request, 'shop/product/about.html')

shop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}

<div id="sidebar">
    {% load static %}
    <div class = "header_logo">
        <img class="company-img" src="{% static 'img/logon.svg' %}" alt="Логотип {{ company_name }}">
    </div>

        <div class="header-right">
            <a class="btn-header" href="{% url 'shop:index' %}">
               <button class="main-btn">Главная</button><img class="img-home" src="{% static 'img/home.png' %}">
            </a>


            <div class="dropdown">

                <a class="btn-header" href="{% url 'shop:product_list' %}" {% if not category %}class="selected"{% endif %}>
                    <button class="dropbtn">Каталог</button><img class="img-burger" src="{% static 'img/burger.svg' %}">
                </a>
                <div class="dropdown-content">
                    {% for c in categories %}
                        <a href="{{ c.get_absolute_url }}" {% if category.slug == c.slug %}class="selected" {% endif %}>{{ c.name }}</a>
                    {% endfor %}
                </div>
            </div>

                <div class="cart">
                    {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                    <a href="{% url 'cart:cart_detail' %}"><img class="img-trash" src="{% static 'img/trash.svg' %}">:</a>
                    <a class = "total_item" href="{% url 'cart:cart_detail' %}">
                        {{total_items}}шт, ₽{{cart.get_total_price}}
                    </a>
                    {%else%}
                    <img class="img-trash" src="{% static 'img/trash.svg' %}">
                    {%endif%}
                    {%endwith%}
                </div>
        </div>
</div>


  <div class = "container_for_trash">
  <h1>Корзина покупок</h1>

      <h4 class="title-contact">Напиши ваши контакты и мы свяжимся с вами</h4>
      <form class="box-contact">
          <input type="email" placeholder="Ваш email">
          <input type="tel" placeholder="Ваш номер телефона">
          <input type="submit" value="Оформить заказ">
      </form>
  <table class="trash">
    <thead>
      <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form class="td-form" action="{% if product.id %}{% url 'cart:cart_add' product.id %}{% endif %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a class="delete" href="{% if product.id %}{% url 'cart:cart_remove' product.id %}{% endif %}">Удалить</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">₽{{ item.price }}</td>
            <td class="num">₽{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всего</td>
        <td colspan="5"></td>
        <td class="num">₽{{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
    </div>





{% endblock %}

shop/myshop/templates/shop/base.html
{% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Мой магазин{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" >
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>   
</head>

<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

shop/myshop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
<div id="sidebar">
    {% load static %}
    <div class = "header_logo">
        <img class="company-img" src="{% static 'img/logon.svg' %}" alt="Логотип {{ company_name }}">
    </div>

        <div class="header-right">
            <a class="btn-header" href="{% url 'shop:index' %}">
               <button class="main-btn">Главная</button><img class="img-home" src="{% static 'img/home.png' %}">
            </a>


            <div class="dropdown">

                <a class="btn-header" href="{% url 'shop:product_list' %}" {% if not category %}class="selected"{% endif %}>
                    <button class="dropbtn">Каталог</button><img class="img-burger" src="{% static 'img/burger.svg' %}">
                </a>
                <div class="dropdown-content">
                    {% for c in categories %}
                        <a href="{{ c.get_absolute_url }}" {% if category.slug == c.slug %}class="selected" {% endif %}>{{ c.name }}</a>
                    {% endfor %}
                </div>
            </div>

                <div class="cart">
                    {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                    <a href="{% url 'cart:cart_detail' %}"><img class="img-trash" src="{% static 'img/trash.svg' %}">:</a>
                    <a class = "total_item" href="{% url 'cart:cart_detail' %}">
                        {{total_items}}шт, ₽{{cart.get_total_price}}
                    </a>
                    {%else%}
                    <img class="img-trash" src="{% static 'img/trash.svg' %}">
                    {%endif%}
                    {%endwith%}
                </div>
        </div>
</div>



  <div class="product-detail">
    <div class="product_detail_titles">
    <img class="product-image" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
      <div class="product_detail_info">
    <h1 class="product-name">{{ product.name }}</h1>
    <div class="product-category-price">
        <div class="product-category">
            <p class="product-category-title">Категория: </p>
          <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
        </div>
            <div class = "product_price">
                <p class="product_price-title">Цена: </p>
                <p class="price">₽{{ product.price }}</p>
              </div>
    </div>
        <div class = "form_styles">
    <form action="{% url 'cart:cart_add' product.id %}" method="post" class="add-to-cart-form">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Добавить в корзину" class="add-to-cart-button">
      </div>
    </form>
        </div>
    </div>
    <div class = "product_title">
    <p class="product-description">{{ product.description|linebreaks }}</p>
      </div>
  </div>

<div class="footer">
    <div class="footer-container">
        <div class="logo">
             <img class="footer-img" src="{% static 'img/kniga3.jpg' %}" alt="Логотип {{ company_name }}">
        </div>

        <div class="footer-content">
            <div class="footer-info">
                <p class="footer-info-upper">Книги которые вы точно запомните!</p>
                <p class="footer-info-bottom">"Чтение — это путешествие, которое можно начать в любое время и в любом месте, открывая перед собой бесконечные миры и бесценные знания."</p>
            </div>
            <div class="footer-bottom">
                <div class="visa">
                    <img src="{% static 'img/Group23.png' %}" alt="Логотип {{ company_name }}">
                </div>
                <div class="footer-right">
                    <p>Содержимое не является публичной офертой</p>
                    <a class="footer-under">Пользовательское соглашение</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/myshop/templates/shop/product/index.html
{% extends 'shop/base.html' %}
{% block title %}Xeon{% endblock %}

{% block content %}



<div id="sidebar">
    {% load static %}
    <div class = "header_logo">
        <img class="company-img" src="{% static 'img/logon.svg' %}" alt="Логотип {{ company_name }}">
    </div>

        <div class="header-right">
            <a class="btn-header" href="{% url 'shop:index' %}">
               <button class="main-btn">Главная</button><img class="img-home" src="{% static 'img/home.png' %}">
            </a>


            <div class="dropdown">

                <a class="btn-header" href="{% url 'shop:product_list' %}" {% if not category %}class="selected"{% endif %}>
                    <button class="dropbtn">Каталог</button><img class="img-burger" src="{% static 'img/burger.svg' %}">
                </a>
                <div class="dropdown-content">
                    {% for c in categories %}
                        <a href="{{ c.get_absolute_url }}" {% if category.slug == c.slug %}class="selected" {% endif %}>{{ c.name }}</a>
                    {% endfor %}
                </div>
            </div>

                <div class="cart">
                    {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                    <a href="{% url 'cart:cart_detail' %}"><img class="img-trash" src="{% static 'img/trash.svg' %}">:</a>
                    <a class = "total_item" href="{% url 'cart:cart_detail' %}">
                        {{total_items}}шт, ₽{{cart.get_total_price}}
                    </a>
                    {%else%}
                    <img class="img-trash" src="{% static 'img/trash.svg' %}">
                    {%endif%}
                    {%endwith%}
                </div>
        </div>
</div>
<div class="main_info">
    <div class="company_info">
        {% load static %}
        <div class = "main-content">
            <p class="main-content-upper">Откройте мир знаний и вдохновения с нами!</p>
            <h1 class="company-h2">Добро пожаловать <br>в наш магазин электронных книг!</h1>
            <p class="main-content-bottom">Откройте мир знаний и вдохновения с нами!<br> Для всех
                возрастов и вкусов, где каждый найдет что-то особенное</p>

            <div class="main-content-price">
                <p class="price-name">Только лицензированные издания</p>
                <p class="price-item">Цена на любой вкус</p>
            </div>
                <a href="{% url 'shop:product_list' %}" {% if not category %}class="selected"{% endif %}>
                <button class="company_button_left">Купить сейчас</button>
            </a>
        </div>
        <div class = "company_info_right">
            <img class="company-img" src="{% static 'img/elkniga.png' %}" alt="Логотип {{ company_name }}">
            <div class="company_info_right-content">

            </div>
        </div>
    </div>

</div>

<div class="footer">
    <div class="footer-container">
        <div class="logo">
             <img class="footer-img" src="{% static 'img/kniga3.jpg' %}" alt="Логотип {{ company_name }}">
        </div>

        <div class="footer-content">
            <div class="footer-info">
                <p class="footer-info-upper">Книги которые вы точно запомните!</p>
                <p class="footer-info-bottom">"Чтение — это путешествие, которое можно начать в любое время и в любом месте, открывая перед собой бесконечные миры и бесценные знания."</p>
            </div>
            <div class="footer-bottom">
                <div class="visa">
                    <img src="{% static 'img/Group23.png' %}" alt="Логотип {{ company_name }}">
                </div>
                <div class="footer-right">
                    <p>Содержимое не является публичной офертой</p>
                    <a class="footer-under">Пользовательское соглашение</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

shop/myshop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}

{% endblock %}

{% block content %}
  <div id="sidebar">
    {% load static %}
    <div class = "header_logo">
        <img class="company-img" src="{% static 'img/logon.svg' %}" alt="Логотип {{ company_name }}">
    </div>

        <div class="header-right">
            <a class="btn-header" href="{% url 'shop:index' %}">
               <button class="main-btn">Главная</button><img class="img-home" src="{% static 'img/home.png' %}">
            </a>


            <div class="dropdown">

                <a class="btn-header" href="{% url 'shop:product_list' %}" {% if not category %}class="selected"{% endif %}>
                    <button class="dropbtn">Каталог</button><img class="img-burger" src="{% static 'img/burger.svg' %}">
                </a>
                <div class="dropdown-content">
                    {% for c in categories %}
                        <a href="{{ c.get_absolute_url }}" {% if category.slug == c.slug %}class="selected" {% endif %}>{{ c.name }}</a>
                    {% endfor %}
                </div>
            </div>

                <div class="cart">
                    {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                    <a href="{% url 'cart:cart_detail' %}"><img class="img-trash" src="{% static 'img/trash.svg' %}">:</a>
                    <a class = "total_item" href="{% url 'cart:cart_detail' %}">
                        {{total_items}}шт, ₽{{cart.get_total_price}}
                    </a>
                    {%else%}
                    <img class="img-trash" src="{% static 'img/trash.svg' %}">
                    {%endif%}
                    {%endwith%}
                </div>
        </div>
</div>

        <div class = "container_for_titles">
                <h1 class="title_for_items">{% if category %}{{ category.name }}{% else %}Весь ассортимент товаров{% endif %}</h1>
                <div id="main" class="product-list">
                {% for product in products %}
                    <div class="container_for_items">
                        <div class="background_for_items">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{ product.name }}">
                        </a>
                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                        <a class="container_for_items-price" href="{{ product.get_absolute_url }}">Цена : ₽ {{ product.price }}</a>
                            </div>
                    </div>
                {% endfor %}
            </div>


<div class="footer">
    <div class="footer-container">
        <div class="logo">
             <img class="footer-img" src="{% static 'img/kniga3.jpg' %}" alt="Логотип {{ company_name }}">
        </div>

        <div class="footer-content">
            <div class="footer-info">
                <p class="footer-info-upper">Книги которые вы точно запомните!</p>
                <p class="footer-info-bottom">"Чтение — это путешествие, которое можно начать в любое время и в любом месте, открывая перед собой бесконечные миры и бесценные знания."</p>
            </div>
            <div class="footer-bottom">
                <div class="visa">
                    <img src="{% static 'img/Group23.png' %}" alt="Логотип {{ company_name }}">
                </div>
                <div class="footer-right">
                    <p>Содержимое не является публичной офертой</p>
                    <a class="footer-under">Пользовательское соглашение</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}